/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package timer;
import javax.swing.*;
import java.io.*;
import java.awt.*;
/**
 *
 * @author FRANKCHUKY
 */
public class Cover extends javax.swing.JFrame {

    /**
     * Creates new form Cover
     */
    public Cover(){
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("icon.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JLABEL_NUMBER = new javax.swing.JLabel();
        JLABEL_EMAIL = new javax.swing.JLabel();
        JLABEL_NAME = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTEXTAREA_DISPLAY = new javax.swing.JTextArea();
        JBUTTON_ABOUT = new javax.swing.JButton();
        JTEXTFIELD_PRESCALER = new javax.swing.JTextField();
        JTEXTFIELD_CRYSTAL = new javax.swing.JTextField();
        JTEXTFIELD_TIME = new javax.swing.JTextField();
        JBUTTON_GENERATE = new javax.swing.JButton();
        JLABEL_TIME = new javax.swing.JLabel();
        JLABEL_CRYSTAL = new javax.swing.JLabel();
        JLABEL_PRESCALER = new javax.swing.JLabel();
        JLABEL_INFORMATION = new javax.swing.JLabel();
        JLABEL_COVER = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TIMER0 CODE GENERATOR");
        setBackground(new java.awt.Color(0, 0, 204));
        setForeground(new java.awt.Color(0, 0, 204));
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setLayout(null);

        JLABEL_NUMBER.setText("07037219055");
        jPanel1.add(JLABEL_NUMBER);
        JLABEL_NUMBER.setBounds(10, 360, 150, 14);

        JLABEL_EMAIL.setText("nwanzechuka1993@gmail.com");
        jPanel1.add(JLABEL_EMAIL);
        JLABEL_EMAIL.setBounds(10, 340, 190, 14);

        JLABEL_NAME.setText("Written by Nwanze Franklin ");
        jPanel1.add(JLABEL_NAME);
        JLABEL_NAME.setBounds(10, 320, 160, 20);

        JTEXTAREA_DISPLAY.setColumns(20);
        JTEXTAREA_DISPLAY.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        JTEXTAREA_DISPLAY.setRows(5);
        jScrollPane1.setViewportView(JTEXTAREA_DISPLAY);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(250, 180, 204, 200);

        JBUTTON_ABOUT.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        JBUTTON_ABOUT.setText("ABOUT");
        JBUTTON_ABOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUTTON_ABOUTActionPerformed(evt);
            }
        });
        jPanel1.add(JBUTTON_ABOUT);
        JBUTTON_ABOUT.setBounds(50, 240, 81, 34);

        JTEXTFIELD_PRESCALER.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        JTEXTFIELD_PRESCALER.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        jPanel1.add(JTEXTFIELD_PRESCALER);
        JTEXTFIELD_PRESCALER.setBounds(250, 50, 204, 34);

        JTEXTFIELD_CRYSTAL.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        JTEXTFIELD_CRYSTAL.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        jPanel1.add(JTEXTFIELD_CRYSTAL);
        JTEXTFIELD_CRYSTAL.setBounds(250, 90, 204, 34);

        JTEXTFIELD_TIME.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        JTEXTFIELD_TIME.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        jPanel1.add(JTEXTFIELD_TIME);
        JTEXTFIELD_TIME.setBounds(250, 130, 204, 34);

        JBUTTON_GENERATE.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        JBUTTON_GENERATE.setText("GENERATE");
        JBUTTON_GENERATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUTTON_GENERATEActionPerformed(evt);
            }
        });
        jPanel1.add(JBUTTON_GENERATE);
        JBUTTON_GENERATE.setBounds(30, 190, 117, 34);

        JLABEL_TIME.setBackground(new java.awt.Color(222, 199, 199));
        JLABEL_TIME.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        JLABEL_TIME.setForeground(new java.awt.Color(255, 0, 0));
        JLABEL_TIME.setText("   TIME IN SECONDS");
        JLABEL_TIME.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true));
        jPanel1.add(JLABEL_TIME);
        JLABEL_TIME.setBounds(10, 130, 160, 34);

        JLABEL_CRYSTAL.setBackground(new java.awt.Color(222, 199, 199));
        JLABEL_CRYSTAL.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        JLABEL_CRYSTAL.setForeground(new java.awt.Color(255, 0, 0));
        JLABEL_CRYSTAL.setText(" XTAL FREQUENCY (MHz)");
        JLABEL_CRYSTAL.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true));
        jPanel1.add(JLABEL_CRYSTAL);
        JLABEL_CRYSTAL.setBounds(10, 90, 160, 34);

        JLABEL_PRESCALER.setBackground(new java.awt.Color(222, 199, 199));
        JLABEL_PRESCALER.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        JLABEL_PRESCALER.setForeground(new java.awt.Color(255, 0, 0));
        JLABEL_PRESCALER.setText("   PRE SCALER (2-256)");
        JLABEL_PRESCALER.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true));
        jPanel1.add(JLABEL_PRESCALER);
        JLABEL_PRESCALER.setBounds(10, 50, 160, 34);

        JLABEL_INFORMATION.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        JLABEL_INFORMATION.setForeground(new java.awt.Color(255, 0, 0));
        JLABEL_INFORMATION.setText("ENTER THE REQUIRED INFORMATION");
        jPanel1.add(JLABEL_INFORMATION);
        JLABEL_INFORMATION.setBounds(80, 10, 310, 20);

        JLABEL_COVER.setIcon(new javax.swing.ImageIcon("C:\\Users\\FRANKCHUKY\\Desktop\\BACKGROUND\\background-desktop-003.jpg")); // NOI18N
        JLABEL_COVER.setAlignmentX(400.0F);
        JLABEL_COVER.setAlignmentY(200.0F);
        jPanel1.add(JLABEL_COVER);
        JLABEL_COVER.setBounds(0, 0, 510, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//action to be performed when the generate button is clicked
    private void JBUTTON_GENERATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUTTON_GENERATEActionPerformed
    double prescaler;
    double crystal;
    double time;
       try{
       prescaler=Double.parseDouble(JTEXTFIELD_PRESCALER.getText());
       crystal=Double.parseDouble(JTEXTFIELD_CRYSTAL.getText());
       time=Double.parseDouble(JTEXTFIELD_TIME.getText());
       String ans=time(prescaler,crystal,time);
       JTEXTAREA_DISPLAY.setText(ans);
       }catch(Exception e){
       JOptionPane.showMessageDialog(null, "ERROR OCCURED WHILE PARSING VALUES", "Input Mismatch Exception", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_JBUTTON_GENERATEActionPerformed

    private void JBUTTON_ABOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUTTON_ABOUTActionPerformed
    String info="This software is meant to\n generate delay routines\n for timer0 register in PIC\n N:B For smaller time\n Use a smaller prescaler";
    JOptionPane.showMessageDialog(null, info, "ABOUT THE SOFTWARE", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_JBUTTON_ABOUTActionPerformed

    private String time(double prescaler,double freq,double time){
        double value=freq/4;
        double number=1/(value*1000000);
        double second=number*prescaler*prescaler;
        double count=time/second;
        int counter=(int)count;
        String get="    movlw "+"d'"+counter+"'\n"+"    movwf counter\n"+"frank:\n"+"    btfss 0bh,2\n"+"    goto frank\n"+"    bcf 0bh,2\n"+"    decfsz counter,1\n"+"    goto frank\n"+"    bcf 0bh,2\n"+"    return";
        return get;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])throws IOException {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
   

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Cover().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBUTTON_ABOUT;
    private javax.swing.JButton JBUTTON_GENERATE;
    private javax.swing.JLabel JLABEL_COVER;
    private javax.swing.JLabel JLABEL_CRYSTAL;
    private javax.swing.JLabel JLABEL_EMAIL;
    private javax.swing.JLabel JLABEL_INFORMATION;
    private javax.swing.JLabel JLABEL_NAME;
    private javax.swing.JLabel JLABEL_NUMBER;
    private javax.swing.JLabel JLABEL_PRESCALER;
    private javax.swing.JLabel JLABEL_TIME;
    private javax.swing.JTextArea JTEXTAREA_DISPLAY;
    private javax.swing.JTextField JTEXTFIELD_CRYSTAL;
    private javax.swing.JTextField JTEXTFIELD_PRESCALER;
    private javax.swing.JTextField JTEXTFIELD_TIME;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
